<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ6eeITy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ6eeITy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ6eeITy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ6eeITy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ6eeITy\App_KernelDevDebugContainer([
    'container.build_hash' => 'J6eeITy',
    'container.build_id' => 'b3bf5231',
    'container.build_time' => 1691478835,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ6eeITy');
