<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPQV2IHF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPQV2IHF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPQV2IHF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPQV2IHF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPQV2IHF\App_KernelDevDebugContainer([
    'container.build_hash' => 'PQV2IHF',
    'container.build_id' => 'dfd135cb',
    'container.build_time' => 1690810060,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPQV2IHF');
